#inferring mRNA from DNA 


dict_possibilities = {'A':4, 'R': 6, 'N':2, 'D':2, 'B':4, 'C':2,
                      'Q':2, 'E':2, 'Z': 4, 'G':4, 'H': 2, 'I':3,
                      'L':6, 'K': 2, 'M': 1, 'F':2, 'P':4,'S':6,
                      'T': 4, 'W': 1, 'Y':2,'V':4}

proteinsequence = 'MVIKAKLKMRKKDWVDWQYCFKKIWGEDLKGWDTHISSRPPQHSKVAVRQAIIMAWGDVHGGTCNNSCINMIHEPFRNYGSETEEEFFCWEHFMSNRFSTFMRHFVHTMEWGHAQANGYGNETYETRVRFVKEDWKEHTPPQSTSCTGATSIDKHCQVVCFPGRFHLRPKDLAVEQRSCMAPQKGWYLSKMPCLVQTISAPKHMKLQCAQVGIRHLEVMWRYQFGTTNMLTTIVSKGEFFWELDKHPCIRHPINKTREDYAMNDKKWENGFHLPMKDQFPPNGNQMAYYYHDRYEVILHTYYHHLNVPSGQFTWVGHLFGMSGYSKTCFPLVCHWFFQYPMYWAKATTACSDQFYIFRQDLDYMVQLPLHENWRGTAVNEWNENADKKTWRPPPITPDIGRKGFFAWTIYLHFICTICGCQTINVCHNTEYWGHPSTKGVKESQRFCSKYMPTRMMVWMTKFARGGISTSCPVLIQTVFAMINNVTLQDDYFGYGWETTNSADLPSERETKGMVLWPDPIYHHKQLEKKHYTCRPKYCNFSITCVDMGDKIQVFWRTVHHHEIVGINGQNPKWSFVQYRLFIWQPKKDGWVWNPITSSWTFNPPRACHELGAVKNLHCTDEADMYMFMPSYQCVLLMLEGFLKKLSSDGDCWHLPNPDFMCVEWVQIGSGALYGNWMCWQPPPIYMDLGPVDKSHFMLLDLIDYMTVCNWWWPTELTEWRENQDIESAACGEMLFQMADLCQITPKEEEWPTLIHLTHGNWGRDHRKEQAPPHPACDYMIKRCHEHDGWVVSFANWIAQAQMHNYYTKETWHACILQERINTYPTCTWEDFLIDVHLTTDSAINKIFSWGYWYDEIDHGDYWNRYIKDKEGWADQQHMGESMFLWKFMKDLKGKANEWGHNQEHYGSRGENPVICLKCFPLGPFLFTTPTILPQWSLGECLFIRELTRWAICTLGTINPGLMWENIACTMYTKEKNVDNGHQSNQPLNQNRGLFMDDV'
possibilities = dict_possibilities[proteinsequence[0]] #will always be 1 because methionine is the start codon 
for element in proteinsequence:
    possibilities = possibilities*dict_possibilities [str(element)]
possibilities = possibilities*3 #stop codon has three possible codons

print (possibilities % 1000000)
